version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    image: jeopardy-php-fpm
    container_name: jeopardy-php-fpm
    working_dir: /var/www
    volumes:
      - ./:/var/www

  webserver:
    image: nginx:alpine
    container_name: jeopardy-nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    ports:
      - 8099:80

  postgres:
    image: postgres:12.9-alpine
    container_name: jeopardy-postgres
    volumes:
      - jeopardydb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - 5099:5432

volumes:
  jeopardydb:
